dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: debian12
    image: docker.io/library/python:3.9.18-bookworm
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible