---
- name: Verify
  hosts: molecule
  gather_facts: true
  tasks:
    - name: Liste des commandes à tester
      ansible.builtin.set_fact:
        commandes_a_tester:
          - "ssh -V"
          - "nvim -v"
          - "htop --version"
          - "tree --version"
          - "tcpdump --version"
          - "mtr --version"
          - "git --version"
          - "rsync --version"
          - "curl --version"
          - "screen --version"
          - "iostat -V"
          - "sudo arp -V"

    - name: Exécuter les commandes à distance
      ansible.builtin.command:
        cmd: "{{ item }}"
      register: resultat_commandes
      loop: "{{ commandes_a_tester }}"
      changed_when: false

    - name: Afficher les stdout
      ansible.builtin.debug:
        var: item.stdout
      loop: "{{ resultat_commandes.results }}"

    - name: Check ssh banner
      ansible.builtin.command:
        cmd: cat /etc/ssh/banner
      register: out
      changed_when: false

    - name: Check ssh banner
      ansible.builtin.debug:
        var: out.stdout_lines
        