#####################
# DEFAULTS-PACKAGES #
#####################
pkg_list:
  - "openssh-client"
  - "openssh-server"
  - "neovim"
  - "sudo"
  - "htop"
  - "tree"
  - "tcpdump"
  - "mtr"
  - "git"
  - "rsync"
  - "curl"
  - "screen"
  - "sysstat"
  - "net-tools"
  - "mtr"

########
# USER #
########

users:
  - name: "helphy"
    password: 
    key: 
