---
- name: Setup default packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    force_apt_get: true
  loop: "{{ pkg_list }}"

- name: Installation Ifupdown2
  ansible.builtin.shell: apt-get install -y ifupdown2 && systemctl restart networking ; sleep 20

- name: Create admin users
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: Administrateur "{{ item.name }}"
    groups: sudo
    password: "{{ item.password | password_hash('sha512') }}"
    append: true
  loop: "{{ users }}"

- name: Deploy SSH Public Key
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"
  loop: "{{ users }}"

- name: Permit root login no
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present

- name: Password Authentication no
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present

- name: Add Banner on ssh login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^Banner'
    line: "Banner /etc/ssh/banner"
    state: present

- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: ssh_banner.j2
    dest: /etc/ssh/banner
    owner: root
    group: root
    mode: '0644'

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
