---
argument_specs:
  main:
    short_description: Config VM after OS-Install
    description:
      - Install some basics configuraitons like default packages, user, and ssh server. On fresh linux install
    author: Mahel 'Helphy' BROSSIER

    options:
      users: 
        type: list
        required: true
        description:
          - Users's list
        elements: dict
        options:
          name:
            description:
              - Username
            type: str
            required: true
          password:
            description:
              - Password's user
            type: str
            required: true
          key:
            description:
              - User Public key for ssh serveur
            type: str
            required: true
      
      pkg_list:
        type: list
        required: true
        description:
          - Default packages
        elements: str

